server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${INITIAL_DB}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: ${SPRING_DATASOURCE_DDL_AUTO}
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    repositories:
      enabled: true
    open-in-view: false
    generate-ddl: true
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type: trace

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  open-ai:
      api-key: ${OPEN_AI_API_KEY}
      model-name: ${OPEN_AI_MODEL_NAME}
      timeout-seconds: 20
#  host-url: ${HOST_URL}
#  client1-url: ${CLIENT1_URL}
#  client2-url: ${CLIENT2_URL}
